
name: 'Proyecto_top'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Proyecto_top:
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_DATABASE_SILVER', 'DEV_PROYECTO_SILVER') }}"
      +schema: STAGING
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_DATABASE_GOLD', 'DEV_PROYECTO_GOLD') }}"
      +schema: CORE

snapshots:
  Proyecto_top:
    +target_database: DEV_PROYECTO_GOLD
    +target_schema: SNAPSHOTS

seeds:
  Proyecto_top:
    +database: DEV_PROYECTO_BRONZE
    +schema: SEEDS